Disable axe color contrast checks
This applies the same patch that was added to jest-axe last year. Without this, you'll see errors like:

```output
Error: Not implemented: window.computedStyle(elt, pseudoElt)
```